Actions で lint が失敗したときに Discord に通知するように
uchikoshi-fes/uchikoshi-fes.jp-2022 pull request #20
Opened 2022-05-05 13:52 UTC by TwoSquirrels

Issue: #17

2022-05-05 13:58 UTC, TwoSquirrels commented
![Screenshot_2022-05-05-22-57-39-72_572064f74bd5f9fa804b05334aa4f912](https://user-images.githubusercontent.com/47352965/166939386-3cebbee5-ad44-4a7d-b8d1-85c7f8434359.jpg)

2022-05-05 16:17 UTC, TwoSquirrels commented
コミットログぐっちゃぐちゃだけど
いい感じにできたのだ！
![Screenshot_2022-05-06-01-16-35-79_572064f74bd5f9fa804b05334aa4f912](https://user-images.githubusercontent.com/47352965/166967549-35fe69a3-0816-4083-919c-88680a4b0181.jpg)

2022-05-05 16:23 UTC, Mogyuchi commented
webhook直接叩こうぜもう

2022-05-05 16:24 UTC, TwoSquirrels commented
とりあえず環境変数は json にするなり
`DISCORD_ID={"TwoSquirrels":"498452350663655424"}`

2022-05-05 17:34 UTC, TwoSquirrels commented
メンションできてないな
明日なおす

2022-05-05 17:35 UTC, Mogyuchi commented
おつ

2022-05-06 11:13 UTC, Mogyuchi requested changes

2022-05-06 11:13 UTC, Mogyuchi commented on package.json
> +    "static": "run-s build export",
PRの内容と違うことをするんじゃないよ
別PRにしましょうね

2022-05-07 02:40 UTC, Mogyuchi commented on package.json
> +    "static": "run-s build export",
対象コミットを revertするだけでもいいと思うよ

2022-05-07 06:08 UTC, TwoSquirrels commented on package.json
> +    "static": "run-s build export",
なるほど

2022-05-07 16:23 UTC, TwoSquirrels commented
結局 `rebase -i` して force push した

2022-05-07 16:25 UTC, TwoSquirrels commented
戻し忘れてた
これで大丈夫かな？

2022-05-07 16:28 UTC, Mogyuchi approved these changes

2022-05-07 16:34 UTC, merged