和モダンにする
uchikoshi-fes/uchikoshi-fes.jp-2022 pull request #205
Opened 2022-08-30 09:29 UTC by gendaineko2222

プレビューURL: https://c6a456ad.uchikoshi-fes-jp-2022.pages.dev/

2022-08-30 09:33 UTC, gendaineko2222 commented
結構大きく変えてみたので、改善したほうが良さそうなところだとか、追加したほうがいいところなどなどあったらここにどんどん書いてってくだせえ！！

2022-08-30 13:47 UTC, gendaineko2222 commented
fixed #189

2022-08-31 11:05 UTC, Mogyuchi commented
> fixed #189

@gendaineko2222 
これ、メモ目的ですか？
イシューのクローズが目的なのであれば一番上のコメント（内部的には `body` )に書いてください🙏

キーワードが記載された場所が分散していると意図せず閉じてしまうという事態が発生しかねないので、`body`の内部のみ検索するようにしています。
https://github.com/uchikoshi-fes/uchikoshi-fes.jp-2022/blob/3cd5ceb3328a82923d35679881eafc5252135979/.github/workflows/close-issues.yml#L27

2022-08-31 13:34 UTC, gendaineko2222 commented
なるほど！
修正しますね

2022-08-31 22:49 UTC, TwoSquirrels commented
あー、明朝体は避けたいかも

2022-08-31 22:49 UTC, TwoSquirrels commented
あと縦書きもいいな

2022-08-31 23:45 UTC, gendaineko2222 commented
> あー、明朝体は避けたいかも

Noto Sans JPに変えて試してみますねー

2022-08-31 23:46 UTC, gendaineko2222 commented
> `public/slogan.svg` はめっちゃいい できれば開催日も欲しいかも

開催日も追加してみます

2022-09-01 01:49 UTC, TwoSquirrels commented
デザイン詳しい人に聞いたら、
黒の半透明は :+1: で、
明朝体はだめだって

2022-09-01 03:04 UTC, Mogyuchi commented
Draft PR にしてくれ頼む

2022-09-01 05:20 UTC, gendaineko2222 commented
> デザイン詳しい人に聞いたら、 黒の半透明は 👍 で、 明朝体はだめだって

たしかに明朝体は一部が細いんで見にくくなることもありますが和風な感じを出すには必要な気がします...
フッターとか開催概要あたりが見にくいのでそこは修正するつもりです
明朝体を使わないのであればゴシック体を使う感じですかね？

![image](https://user-images.githubusercontent.com/93499945/187836628-2ca5c697-d20a-487d-a30f-5dc6e0deb8b2.png)
![image](https://user-images.githubusercontent.com/93499945/187836643-8f062e90-b5c5-49bf-85f0-6cebec4183cc.png)

2022-09-01 06:09 UTC, TwoSquirrels commented
そもそも縦書きっていうのが難易度高いからね

2022-09-01 07:11 UTC, gendaineko2222 commented
> そもそも縦書きっていうのが難易度高いからね

別に明朝体だからといって縦書きにしなくてもいいと思います
というか縦書きにしたら良さそうな要素がないんですよね...
アクセスとか日程を縦書きにするわけにもいかないし...

2022-09-01 13:12 UTC, TwoSquirrels commented
横書きが無難かなーとは思う

2022-09-01 13:13 UTC, TwoSquirrels commented
あと、SNS のボタンの角丸は微妙かも

2022-09-01 14:59 UTC, gendaineko2222 commented
> あと、SNS のボタンの角丸は微妙かも

おけです
修正しますー

2022-09-05 00:18 UTC, Mogyuchi commented
svg内のフォントはアウトライン化推奨です！

2022-09-05 02:45 UTC, gendaineko2222 commented
ありゃ
できてないすかね
家帰ってから確認しますね

2022-09-05 02:46 UTC, gendaineko2222 commented
#197 と調整します

2022-09-05 23:15 UTC, TwoSquirrels commented
コンフリクト凄いことなってるので頑張ってください (おい)

2022-09-11 02:16 UTC, gendaineko2222 commented
トップページ終わったのでreadyにします

2022-09-11 03:30 UTC, Mogyuchi requested changes
コンフリクトのやつめっちゃ残ってる；；
対応可ですか？

2022-09-11 03:30 UTC, Mogyuchi commented on README.md
> +<<<<<<< HEAD
あいうえお

2022-09-11 03:32 UTC, gendaineko2222 commented on README.md
> +<<<<<<< HEAD
lintにかからなくて見逃してたー
対応します

2022-09-11 09:33 UTC, Mogyuchi commented
@gendaineko2222 
ほかのところにもあるんですよ。。。
`<<<<<<< HEAD` で探してください

2022-09-11 11:44 UTC, gendaineko2222 commented
ほんとだ...
なんでなんも出てこないんだろ...
直します

2022-09-11 11:57 UTC, gendaineko2222 commented
今度こそできたと思います！
多分()

2022-09-11 12:04 UTC, Mogyuchi requested changes
package-lock.json 消してください

2022-09-11 13:38 UTC, Mogyuchi commented
コンフリクト解消頼みます

コンフリクト状態にしたあと、ロックファイルと node_modules 消して pnpm i すればおけだとおもいます

2022-09-12 00:30 UTC, gendaineko2222 commented
できますた

2022-09-12 01:49 UTC, TwoSquirrels commented
最新版のプレビューってどこにあるんだ...
https://feature--88-create-a-japanes.uchikoshi-fes-jp-2022.pages.dev/
は古い気が

2022-09-12 04:02 UTC, Mogyuchi commented
https://github.com/gendaineko2222/uchikoshi-fes.jp-2022/runs/8296502955
ぴえん

2022-09-12 04:23 UTC, gendaineko2222 commented
ぴえん
とりあえずcodespacesのリンク共有します
https://gendaineko2222-uchikoshi-fes-jp-2022-pj9p45rj9h7j95-3000.githubpreview.dev/
<details>
<summary>cloudflare pageのログです</summary>

```
2022-09-12T00:30:31.639397Z	Cloning repository...
2022-09-12T00:30:34.625095Z	From https://github.com/gendaineko2222/uchikoshi-fes.jp-2022
2022-09-12T00:30:34.625652Z	 * branch            f552f33999cc498148b4c8bca6283d7e26ef4163 -> FETCH_HEAD
2022-09-12T00:30:34.625916Z	
2022-09-12T00:30:34.867949Z	HEAD is now at f552f33 Merge branch 'develop' of https://github.com/uchikoshi-fes/uchikoshi-fes.jp-2022 into feature/#88_Create_a_Japanese_modern_look
2022-09-12T00:30:34.869483Z	
2022-09-12T00:30:35.052094Z	
2022-09-12T00:30:35.09818Z	Success: Finished cloning repository files
2022-09-12T00:30:35.791203Z	Installing dependencies
2022-09-12T00:30:35.799472Z	Python version set to 2.7
2022-09-12T00:30:37.569013Z	Attempting node version '16.17.0' from .node-version
2022-09-12T00:30:39.033669Z	Downloading and installing node v16.17.0...
2022-09-12T00:30:39.393503Z	Downloading https://nodejs.org/dist/v16.17.0/node-v16.17.0-linux-x64.tar.xz...
2022-09-12T00:30:40.0989Z	Computing checksum with sha256sum
2022-09-12T00:30:40.219553Z	Checksums matched!
2022-09-12T00:30:43.861376Z	Now using node v16.17.0 (npm v8.15.0)
2022-09-12T00:30:44.171671Z	Started restoring cached build plugins
2022-09-12T00:30:44.182465Z	Finished restoring cached build plugins
2022-09-12T00:30:44.56841Z	Attempting ruby version 2.7.1, read from environment
2022-09-12T00:30:47.295625Z	Using ruby version 2.7.1
2022-09-12T00:30:47.59346Z	Using PHP version 5.6
2022-09-12T00:30:47.722011Z	5.2 is already installed.
2022-09-12T00:30:47.743048Z	Using Swift version 5.2
2022-09-12T00:30:47.743452Z	Started restoring cached node modules
2022-09-12T00:30:47.756559Z	Finished restoring cached node modules
2022-09-12T00:30:48.156712Z	Installing NPM modules using NPM version 8.15.0
2022-09-12T00:30:48.492162Z	npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
2022-09-12T00:30:48.492467Z	npm WARN config location in the cache, and they are managed by
2022-09-12T00:30:48.492667Z	npm WARN config     [`cacache`](http://npm.im/cacache).
2022-09-12T00:30:48.822002Z	npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
2022-09-12T00:30:48.822268Z	npm WARN config location in the cache, and they are managed by
2022-09-12T00:30:48.82246Z	npm WARN config     [`cacache`](http://npm.im/cacache).
2022-09-12T00:31:13.63462Z	npm WARN deprecated txt-ast-traverse@1.2.1: See https://github.com/textlint/textlint/issues/455
2022-09-12T00:31:25.417032Z	
2022-09-12T00:31:25.417387Z	> uchikoshi-fes.jp-2022@1.2.1 prepare
2022-09-12T00:31:25.417502Z	> husky install || [ $? = 127 ]
2022-09-12T00:31:25.417598Z	
2022-09-12T00:31:25.531065Z	husky - Git hooks installed
2022-09-12T00:31:25.587659Z	
2022-09-12T00:31:25.587976Z	added 1301 packages, and audited 1302 packages in 37s
2022-09-12T00:31:25.588134Z	
2022-09-12T00:31:25.588286Z	274 packages are looking for funding
2022-09-12T00:31:25.588401Z	  run `npm fund` for details
2022-09-12T00:31:25.590138Z	
2022-09-12T00:31:25.590328Z	found 0 vulnerabilities
2022-09-12T00:31:25.6105Z	NPM modules installed
2022-09-12T00:31:26.063765Z	npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
2022-09-12T00:31:26.064035Z	npm WARN config location in the cache, and they are managed by
2022-09-12T00:31:26.064158Z	npm WARN config     [`cacache`](http://npm.im/cacache).
2022-09-12T00:31:26.080075Z	Installing Hugo 0.54.0
2022-09-12T00:31:26.741489Z	Hugo Static Site Generator v0.54.0-B1A82C61A/extended linux/amd64 BuildDate: 2019-02-01T10:04:38Z
2022-09-12T00:31:26.74494Z	Started restoring cached go cache
2022-09-12T00:31:26.761005Z	Finished restoring cached go cache
2022-09-12T00:31:26.879433Z	go version go1.14.4 linux/amd64
2022-09-12T00:31:26.892075Z	go version go1.14.4 linux/amd64
2022-09-12T00:31:26.894749Z	Installing missing commands
2022-09-12T00:31:26.895188Z	Verify run directory
2022-09-12T00:31:26.895412Z	Executing user command: next build && next export
2022-09-12T00:31:27.364003Z	{
2022-09-12T00:31:27.364269Z	  reactStrictMode: true,
2022-09-12T00:31:27.364386Z	  pageExtensions: [ 'js', 'jsx', 'md', 'mdx' ],
2022-09-12T00:31:27.364487Z	  webpack: [Function: webpack],
2022-09-12T00:31:27.364579Z	  env: { isProduct: false },
2022-09-12T00:31:27.364669Z	  images: { loader: 'custom' }
2022-09-12T00:31:27.364757Z	}
2022-09-12T00:31:27.375213Z	warn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
2022-09-12T00:31:27.444897Z	Attention: Next.js now collects completely anonymous telemetry regarding usage.
2022-09-12T00:31:27.445188Z	This information is used to shape Next.js' roadmap and prioritize features.
2022-09-12T00:31:27.445302Z	You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
2022-09-12T00:31:27.445412Z	https://nextjs.org/telemetry
2022-09-12T00:31:27.44551Z	
2022-09-12T00:31:27.560046Z	info  - Linting and checking validity of types...
2022-09-12T00:31:30.061515Z	info  - Creating an optimized production build...
2022-09-12T00:31:33.171554Z	{
2022-09-12T00:31:33.171905Z	  reactStrictMode: true,
2022-09-12T00:31:33.172032Z	  pageExtensions: [ 'js', 'jsx', 'md', 'mdx' ],
2022-09-12T00:31:33.172126Z	  webpack: [Function: webpack],
2022-09-12T00:31:33.172217Z	  env: { isProduct: false },
2022-09-12T00:31:33.172307Z	  images: { loader: 'custom' }
2022-09-12T00:31:33.172404Z	}
2022-09-12T00:31:33.325626Z	info  - using build directory: /opt/buildhome/repo/.next
2022-09-12T00:31:33.326484Z	Error: Could not find a production build in the '/opt/buildhome/repo/.next' directory. Try building your app with 'next build' before starting the static export. https://nextjs.org/docs/messages/next-export-no-build-id
2022-09-12T00:31:33.326677Z	    at /opt/buildhome/repo/node_modules/next/dist/export/index.js:59:19
2022-09-12T00:31:33.326783Z	    at async Span.traceAsyncFn (/opt/buildhome/repo/node_modules/next/dist/trace/trace.js:79:20)
2022-09-12T00:31:33.345031Z	Failed: build command exited with code: 1
2022-09-12T00:31:34.309961Z	Failed: an internal error occurred
```
</details>

2022-09-12 04:36 UTC, Mogyuchi commented
ビルド再試行できますか

2022-09-12 04:46 UTC, gendaineko2222 commented
> ビルド再試行できますか

licenseページでエラー出て止まってしまいます...
```
13:44:50.932 | > Build error occurred
-- | --
13:44:50.932 | Error: Export encountered errors on following paths:
13:44:50.932 | /licenses
13:44:50.932 | at /opt/buildhome/repo/node_modules/next/dist/export/index.js:394:19
13:44:50.933 | at runMicrotasks (<anonymous>)
13:44:50.933 | at processTicksAndRejections (node:internal/process/task_queues:96:5)
13:44:50.933 | at async Span.traceAsyncFn (/opt/buildhome/repo/node_modules/next/dist/trace/trace.js:79:20)
13:44:50.933 | at async /opt/buildhome/repo/node_modules/next/dist/build/index.js:1168:21
13:44:50.933 | at async Span.traceAsyncFn (/opt/buildhome/repo/node_modules/next/dist/trace/trace.js:79:20)
13:44:50.933 | at async /opt/buildhome/repo/node_modules/next/dist/build/index.js:1044:17
13:44:50.933 | at async Span.traceAsyncFn (/opt/buildhome/repo/node_modules/next/dist/trace/trace.js:79:20)
13:44:50.933 | at async Object.build [as default] (/opt/buildhome/repo/node_modules/next/dist/build/index.js:65:29)
13:44:50.974 | Failed: build command exited with code: 1
13:44:51.805 | Failed: an internal error occurred
```

2022-09-12 23:21 UTC, Mogyuchi commented
むむー

2022-09-13 01:32 UTC, gendaineko2222 commented
うう

2022-09-13 14:29 UTC, Mogyuchi approved these changes
わからん

2022-09-13 14:42 UTC, TwoSquirrels commented
#260

2022-09-13 15:55 UTC, Mogyuchi commented
ごめんおまたせ

2022-09-13 23:40 UTC, gendaineko2222 commented
いけました！
https://10080938.uchikoshi-fes-jp-2022.pages.dev/

2022-09-14 06:17 UTC, TwoSquirrels commented
おお

2022-09-14 06:24 UTC, TwoSquirrels commented
めっちゃすげぇ

2022-09-14 06:24 UTC, TwoSquirrels commented
明朝体は一部にしたほうがいいって言うけど、
それ以外は完璧だと思う

2022-09-14 06:59 UTC, TwoSquirrels commented
あー、マップは川崎か横浜すくなくとも一方が入る縮尺がいいかも
(デバイスによって入ったり入らなかったりするので注意)

2022-09-14 07:00 UTC, Mogyuchi commented
いったんマージして別PRにしたほうが良いのでは

2022-09-14 13:42 UTC, gendaineko2222 commented
明朝体に関しては本文をゴシックにしたりして試したんですけど、違和感がどうしてもでちゃって
可読性もそこまで低いわけではないので妥協じゃだめですか(
マップは別prでやりますー

2022-09-14 14:55 UTC, TwoSquirrels commented
それ以外はゴシックだって

2022-09-14 15:00 UTC, TwoSquirrels commented
![image](https://user-images.githubusercontent.com/47352965/190190777-06903785-5c75-4d1e-809b-cee6bc680c69.png)
とのこと

2022-09-14 15:01 UTC, TwoSquirrels commented
フォントって結構大事らしいから、そこだけいい感じにしたらあとは別 PR かな

2022-09-14 23:37 UTC, gendaineko2222 commented
おけです！

2022-09-15 05:55 UTC, Mogyuchi commented
あかん

2022-09-15 05:56 UTC, Mogyuchi requested changes
なぜだかわからんが、
サイドメニューおしてページ移動したあと、スクロールができなくなる

2022-09-15 07:46 UTC, TwoSquirrels commented
wtf

2022-09-15 11:48 UTC, Mogyuchi requested changes

2022-09-15 11:48 UTC, Mogyuchi commented on components/layout/layout.module.scss
> -  overflow: auto;
これを消したせいらしい

2022-09-15 13:44 UTC, gendaineko2222 commented on components/layout/layout.module.scss
> -  overflow: auto;
これの代替でfixedをbodyにつけてるんですけどそれがうまくいってないのかも...
overflowを消したのはscrollイベントが動かなくなるからなんです...

2022-09-15 16:31 UTC, Mogyuchi commented on components/layout/layout.module.scss
> -  overflow: auto;
ここはさわらなくておけ

2022-09-16 01:56 UTC, gendaineko2222 commented on components/layout/layout.module.scss
> -  overflow: auto;
overflowがスクロールイベントを邪魔するバグがあるっぽいんすよ
ナビゲーションバーを透明から白にするアニメーションにスクロール位置を使っているのでここを変えざるを得ないんです

2022-09-16 02:34 UTC, Mogyuchi commented
Actions；；

2022-09-16 03:14 UTC, Mogyuchi commented on components/layout/layout.module.scss
> -  overflow: auto;
> ここはさわらなくておけ
あ、戻さなくていいの意
ややこしくてすまん

2022-09-16 11:08 UTC, Mogyuchi commented
https://react-spectrum.adobe.com/react-aria/usePreventScroll.html
これ使ってみてください

2022-09-16 22:59 UTC, gendaineko2222 commented
おけです

2022-09-17 00:01 UTC, TwoSquirrels commented
## TODO
- [ ] スクロール直す
- [ ] 明朝体を一部だけにする
- [ ] どこにも使われてない svg 消す
- [ ] 画像は `@/components/base/image` を使う

2022-09-17 02:55 UTC, Mogyuchi commented
なんかロックファイルに差分があるな
develop側正で大丈夫なはず

2022-09-17 05:42 UTC, gendaineko2222 commented
一気に終わらせまーす
usePreventScrollがうまく使えない
むう...

2022-09-17 07:16 UTC, gendaineko2222 commented
かんりょー
https://e2109151.uchikoshi-fes-jp-2022.pages.dev/

2022-09-17 09:14 UTC, TwoSquirrels commented
スクロールどうなってる？

2022-09-17 09:18 UTC, Mogyuchi commented
「スクロールはしない👍」

2022-09-17 09:31 UTC, TwoSquirrels approved these changes
いろいろあるけどマージです！
おめでとう！ありがとう！
デザインセンスはプロ！

2022-09-17 09:31 UTC, merged

2022-09-17 09:55 UTC, gendaineko2222 commented on components/variables.scss
> +$color-base: #fff;
たしかに
調べてみた感じだと白から少しずらした色のほうが雰囲気でていいとか
時間あるので直しときます

2022-09-17 09:57 UTC, gendaineko2222 commented on pages/global.scss
> +  height: 100%;
sanitize.cssのやつを打ち消してるだけなので影響は多分ないと思うんですけど、マップのサイズが変わらないときに試したやつの残骸なので消しときます(iframeの性質についてよくわかってなかった)

2022-09-17 09:57 UTC, gendaineko2222 commented on pages/index.module.scss
> +  height: 100dvh;
これも対策しますー

2022-09-17 10:01 UTC, Mogyuchi commented on .vscode/settings.json
> +    "editor.defaultFormatter": "redhat.vscode-xml"
消しときます

2022-09-17 10:03 UTC, gendaineko2222 commented on public/icons/google-map-icon.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 150 150"><path fill="#1a73e8" d="M89.77 10.4c-4.4-1.39-9.08-2.15-13.94-2.15-14.18 0-26.87 6.41-35.33 16.48l21.8 18.34L89.77 10.4z"/><path fill="#e
https://github.com/uchikoshi-fes/uchikoshi-fes.jp-2022/pull/205/commits/f133bd0d42ef23c5aae6b4379da96abbba757d91
でけしたはずなのになぜだ
消しときます

2022-09-17 10:10 UTC, gendaineko2222 commented on pages/index.module.scss
> +  background-image: url("/souichiro.jpeg");
https://github.com/uchikoshi-fes/uchikoshi-fes.jp-2022/pull/205/commits/16af79da93a06a0dca2bce41bdb211351f84d7e4
でなおしたはずなのにい
プルするときにミスった...