Version 0.1.0
uchikoshi-fes/uchikoshi-fes.jp-2022 pull request #28
Opened 2022-05-08 14:44 UTC by TwoSquirrels

プレビュー: https://560e2d66.uchikoshi-fes-2022.pages.dev/

# 主な変更点

- Next.js のセットアップ
  #1 
- 開発補助ツールのセットアップ (Actions, Prettier, textlint, githooks, jest 等)
  #6 #7 #8 #9 #13 #14 #16 #19 #20 #27 
- Issue フォーム導入
  #26

2022-05-08 14:52 UTC, Mogyuchi commented on README.md
> +**Latest Update:** 2022/MM/DD
うん。

2022-05-08 14:53 UTC, Mogyuchi commented on README.md
> +GitHub アカウントをお持ちの場合は [Issues](/issues) に、
このリンク多分期待通りに動かないんだよね

2022-05-08 15:01 UTC, TwoSquirrels commented on README.md
> +**Latest Update:** 2022/MM/DD
MM/DD のままだった...

2022-05-08 15:01 UTC, TwoSquirrels commented on README.md
> +GitHub アカウントをお持ちの場合は [Issues](/issues) に、
まじか
どうするのが最適かな？

2022-05-08 15:02 UTC, Mogyuchi commented on README.md
> +GitHub アカウントをお持ちの場合は [Issues](/issues) に、
URL全体載せるのが良いと思う
ローカルからでもそしたら飛べるし

2022-05-08 15:04 UTC, TwoSquirrels commented on README.md
> +GitHub アカウントをお持ちの場合は [Issues](/issues) に、
軽く調べた感じ絶対パスっぽそうだけど

2022-05-08 15:22 UTC, Mogyuchi commented on README.md
> +GitHub アカウントをお持ちの場合は [Issues](/issues) に、
それってどこ見て言ってる？

2022-05-08 15:32 UTC, Mogyuchi commented on README.md
> +GitHub アカウントをお持ちの場合は [Issues](/issues) に、
![image](https://user-images.githubusercontent.com/69337624/167303199-88cfc86a-937a-416b-8102-eaebbeaff78f.png)
上のようにローカルで開けなくなるのを回避するために
https: から書いてるプロジェクトが多いイメージ
というより そう書いてないプロジェクトを見たおぼえがない

2022-05-08 16:18 UTC, TwoSquirrels commented on README.md
> +GitHub アカウントをお持ちの場合は [Issues](/issues) に、
fixed #29

2022-05-08 17:28 UTC, Mogyuchi requested changes
favicon.ico は削除しておいたほうが良い

一部のブラウザ(iPadOS Safariなど)で、キャッシュされてしまってどうしようもなくなる

2022-05-08 22:27 UTC, TwoSquirrels commented
まじか

2022-05-09 02:40 UTC, TwoSquirrels commented
これでもう merge しちゃっていいのかな

2022-05-09 02:50 UTC, Mogyuchi approved these changes

2022-05-09 02:51 UTC, Mogyuchi commented
おけやで

2022-05-09 07:33 UTC, TwoSquirrels commented
まあぁぁぁーーーーー

2022-05-09 07:33 UTC, merged

2022-05-09 07:33 UTC, TwoSquirrels commented
じ！