パッケージマネージャーを pnpm に変更
uchikoshi-fes/uchikoshi-fes.jp-2022 pull request #39
Opened 2022-05-13 03:07 UTC by Mogyuchi

close #38 

# 変更内容
- package.json
  - packageManager フィールドを追加
    - for corepack
  - engines フィールドを追加
    - npm 禁止
  - Unmet peer dependencies を `dev dependencies` として追加
    - @textlint/ast-node-types
    - @textlint/types
    - textlint-rule-preset-ja-spacing
    - typescript
- .npmrc
  - npm の使用を禁止
  - 不足する `peer dependencies` を `dev dependencies` として自動的に インストール
  - add 時に exact version でパッケージを記載
- GitHub Actions を修正
- DEVELOP.md を修正

2022-05-13 23:02 UTC, TwoSquirrels commented
>         * textlint-rule-preset-ja-spacing

たぶんこれ json の差分の `,` のせいで勘違いしてる

2022-05-13 23:07 UTC, TwoSquirrels commented
https://github.com/uchikoshi-fes/uchikoshi-fes.jp-2022/pull/39/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R30
`prepare` は実行される？

2022-05-14 03:16 UTC, Mogyuchi commented
> > ```
> > "prepare": "husky install"
> > ```
> 
> 
> `prepare` は実行される？

当然される
![7C15E873-2CB1-4623-AF21-257BFC073173](https://user-images.githubusercontent.com/69337624/168408778-9cd3687c-f15d-47f0-a71a-ddb0958dfe1a.jpeg)

2022-05-14 03:17 UTC, Mogyuchi commented
> > ```
> >     * textlint-rule-preset-ja-spacing
> > ```
> 
> 
> たぶんこれ json の差分の `,` のせいで勘違いしてる

edited

2022-05-14 08:26 UTC, Mogyuchi commented
Cloudflare Pages で pnpm を使う場合は ビルドコマンドを下記のものに変えてください
```console
rm -rf node_modules && corepack enable && pnpm install --store=node_modules/.pnpm-store --frozen-lockfile && pnpm static
```

2022-05-16 16:50 UTC, TwoSquirrels requested changes
あ、
https://github.com/uchikoshi-fes/uchikoshi-fes.jp-2022/blob/a812cb83803144ae735fb20b671c2bc16fd43608/.husky/pre-commit#L4
ここ、 `npx` じゃなくて `pnpm` にしたほうがいいかも？

2022-05-16 16:55 UTC, TwoSquirrels approved these changes

2022-05-16 17:09 UTC, TwoSquirrels commented
まーじ！

2022-05-16 17:09 UTC, merged